#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw{open};
use Cwd qw{getcwd chdir};

my $dir = getcwd;

my $rakudodir = $1 if $dir =~ m!^(.+)/t/spec.*$!;

my @git_status_lines = `git status`;
my @changed_files;

for my $statuslines (@git_status_lines) {
    push @changed_files, $1 if $statuslines =~ /^\#\s*modified:\s+(.+)$/;
}

chdir $rakudodir;
my @outputs;
my %plans_wrong;
for my $file (@changed_files) {
    my @output = `make t/spec/$file`;
    for my $line (@output) {
         $plans_wrong{$file} = $line if( $line =~ /Bad plan\./i );
    }
}

chdir $dir;

if(keys(%plans_wrong) > 0) {
    for my $key (keys %plans_wrong) {
        warn "Adjusting wrong plans for $key...";
        my ($wrong, $right) = $plans_wrong{$key} =~ /(\d+).+(\d+)/;
        open my $fhandle, '+<', $key;
        my @lines = $fhandle;
        for my $line (@lines) {
            $line =~ s/$wrong/$right/ if $line eq $plans_wrong{$key};
            print $fhandle $line;
        }
        close $fhandle;
        warn "Restaging $key with an adjusted plan.";
        `git add $key`;
    }
}
